import type { Metadata } from "next";
import "@/app/globals.css";

import Header from "../../../components/dashboard/TopBar";
import Sidebar from "../../../components/dashboard/Sidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function salesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
        <div className="flex min-h-screen bg-gray-100 dark:bg-[#18181b]">
              <Sidebar />
              <div className="flex-1 flex flex-col">
                <Header />
                <main className="flex-1 p-6">
                 {children}
                </main>
              </div>
            </div>
          
      
  );
}
